#!/bin/bash

#PBS -N bagging_pcm
#PBS -o logs/bagging_%J_%I.out
#PBS -e logs/bagging_%J_%I.err

#PBS -J 0-23

#PBS -l select=1:ncpus=4:mem=16gb
#PBS -l walltime=72:00:00

cd "$PBS_O_WORKDIR" || exit 1

module purge

module load gcc/14.2.0
module load python/3.12.8
module load pcre2/10.44

export R_HOME=$HOME/master_thesis/ggkm/utils/R-4.4.3
export LD_LIBRARY_PATH=$R_HOME/lib:$LD_LIBRARY_PATH

source ~/venvs/master_thesis/bin/activate

echo "Job ID: $PBS_JOBID"
echo "Task ID: $PBS_ARRAY_INDEX"
echo "Host: $(hostname)"
echo "Date: $(date)"

python -u -m ggkm.scripts.run_bagging_experiment

echo "Finished"
echo "Date: $(date)"
