#!/bin/bash

#PBS -N feature_selection

#PBS -l select=1:ncpus=4:mem=24gb
#PBS -l walltime=288:00:00


cd "$PBS_O_WORKDIR" || exit 1


mkdir -p logs


exec > logs/feature_selection_${PBS_JOBID}.out
exec 2> logs/feature_selection_${PBS_JOBID}.err


echo "=================================="
echo "Job ID: $PBS_JOBID"
echo "Host: $(hostname)"
echo "Start: $(date)"
echo "=================================="


TASK_START=$(date +%s)


module purge

module load gcc/14.2.0
module load python/3.12.8
module load pcre2/10.44


export R_HOME=$HOME/master_thesis/ggkm/utils/R-4.4.3
export LD_LIBRARY_PATH=$R_HOME/lib:$LD_LIBRARY_PATH


source ~/venvs/master_thesis/bin/activate


echo "Python:"
which python
python --version


python -u -m ggkm.scripts.run_feature_selection


TASK_END=$(date +%s)

ELAPSED=$((TASK_END - TASK_START))


echo ""
echo "=================================="
echo "Finished: $(date)"
echo "Elapsed seconds: $ELAPSED"
echo "Elapsed minutes: $(awk "BEGIN {printf \"%.2f\", $ELAPSED/60}")"
echo "=================================="
