#!/bin/bash

#PBS -N bc_bagging
#PBS -J 0-11

#PBS -l select=1:ncpus=4:mem=16gb
#PBS -l walltime=336:00:00

cd "$PBS_O_WORKDIR" || exit 1

mkdir -p logs

# One output/error file per array task
exec > "logs/bc_bagging_${PBS_JOBID}_${PBS_ARRAY_INDEX}.out"
exec 2> "logs/bc_bagging_${PBS_JOBID}_${PBS_ARRAY_INDEX}.err"


echo "=================================="
echo "PBS Job ID: $PBS_JOBID"
echo "PBS Array ID: $PBS_ARRAY_ID"
echo "PBS Task ID: $PBS_ARRAY_INDEX"
echo "Host: $(hostname)"
echo "Start: $(date)"
echo "=================================="


module purge

module load gcc/14.2.0
module load python/3.12.8
module load pcre2/10.44


export R_HOME=$HOME/master_thesis/ggkm/utils/R-4.4.3
export LD_LIBRARY_PATH=$R_HOME/lib:$LD_LIBRARY_PATH


source ~/venvs/master_thesis/bin/activate


echo "Python:"
which python
python --version

echo ""
echo "Running experiment..."
echo ""


python -u -m ggkm.scripts.run_breast_cancer_bagging_random


echo ""
echo "=================================="
echo "Finished: $(date)"
echo "=================================="
